# Generated by Django 2.2.6 on 2019-10-16 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dynamicadmin', '0001_initial'),
        ('example_bundle', '0002_exampletaxonomydictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='example_bundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('on_char_field', models.CharField(blank=True, default='', max_length=255, verbose_name='char field 1')),
                ('bundle', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='example_bundle.ExampleBundle')),
                ('some_name', models.ForeignKey(blank=True, limit_choices_to={'dictionary': 1}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='dynamicadmin.TaxonomyTerm', verbose_name='list ref')),
            ],
            options={
                'verbose_name': 'example bundle',
                'verbose_name_plural': 'example bundle',
            },
        ),
    ]
